### ISSUE TITLE
Separate tech-preview from supported image-streams

### ISSUE THREAD

**Issue by sspeiche** [jboss-openshift/application-templates#390]
I did some investigation on ways to handle shipping separately supported versus tech preview content. Currently the file https://github.com/jboss-openshift/application-templates/blob/master/jboss-image-streams.json contains both. It isn't possible to install just the supported image-streams with this file.

I investigated 2 approaches for how best to do this.
1. Move the tech preview definition to another file and reuse the same image-stream name. Then just `oc apply -f tech-preview-image-stream.json -n openshift` to overlay the tech-preview tags. Though this doesn't work as the `apply` function instead merged the results, replacing the supported tags with the tech-preview ones. So this approach doesn't work.

2. Move the tech preview definition to another file and use a NEW image-stream name, such as <existing name>-techpreview. This seemed to work fairly and gives the flexibility of installing either or both the supported image-streams and the tech-preview ones.

@rcernich @bparees thoughts?

**Comment by sspeiche** [comment]
Doesn't look to bad as separate entries. Perhaps in the future we can tag them and add a filter like RHCC. 
![screen shot 2017-10-22 at 10 51 43 pm](https://user-images.githubusercontent.com/727196/31870373-9cf25810-b77b-11e7-94a4-bcef3f13daa3.png)

Let me know and I can make the change if needed as well.

**Comment by bparees** [comment]
the second option sounds ok to me.

option 1 could be made to work if tech preview was added to the names of the tags, and might be preferable since it wouldn't double the number of imagestreams, but it is slightly more work to maintain the file since the tags have a different name.

**Comment by rcernich** [comment]
Is this even an issue, since all the image streams are now "hidden?"  The plan going forward is to keep the TP tag pointed to the latest released image, which will either be GA or TP, depending on whether or not the latest sprint was released as TP or GA.  (The idea being that folks that try TP will be able to pick up the latest image, which may be GA.)

I think this is a bigger issue with the templates, as that's how all our images are actually exposed to end users.  Since we don't have a way to present parallel streams (either in the product or maintenance of templates themselves, i.e. we don't want to dup' all these), I don't think this is something we really need to worry about.  The plan for TP releases is to just advise users to use the paste/import YAML capability in "add to project".  As the image stream definitions will not be made available to the installer, that also means users will need to import the streams into their own projects (e.g. for online) and use those.

HTH

**Comment by sspeiche** [comment]
The fact they are "hidden" helps, though there are other areas where the tags will be exposed completely. As long as we are ok with them being park of that, it is fine.

You can parameterize the tags the templates use and describe they can change it. This is how it is done with origin templates. 

So I think we agree we are not going to split out the tech-preview for now. Closing...
